### ISSUE TITLE
LDD-1321 uses different API commands

### ISSUE THREAD

**Issue by dstr951** [meerstetter/pyMeCom#26]
when metype is equal to 'LDD', a set of commands is added to support LDD queries.
I tried using it with my LDD but the commands aren't compatible. When I use my device with the current command, I get an error that the device return 'unknown parameter'. I tried fixing it locally by changing the command according to the table specified in the following file:
[LDD-1321 Communication Protocol 5294A.pdf](https://github.com/spomjaksilp/pyMeCom/files/14013313/LDD-1321.Communication.Protocol.5294A.pdf)

I suggest creating another metype called "LDD-1321" and create a separate command table for it. I can also perform the fix if you will give me a green light

**Comment by timhellwig** [comment]
Please go ahead. The original contributor and myself are not actively using / developing the driver anymore so we are very open for contributions.

**Comment by samirceka** [comment]
Since the changes have been merged I consider this issue to be resolved.
Feel free to reopen it if you disagree.
